### ISSUE TITLE
Select Commercial Catdoor

### ISSUE THREAD

**Issue by nagn** [gt-catdoor/catdoor#1]
https://www.homedepot.com/p/Ideal-Pet-6-25-in-x-6-25-in-Small-Cat-Flap-Cat-Door-with-Plastic-Frame-And-Rigid-Flap-SPF/100404349?MERCH=REC-_-PIPHorizontal2_rr-_-100423170-_-100404349-_-N

**Comment by shott6** [comment]
We are choosing this cat door: https://www.homedepot.com/p/Ideal-Pet-6-25-in-x-6-25-in-Small-Cat-Flap-Cat-Door-with-Plastic-Frame-And-Rigid-Flap-SPF/100404349?MERCH=REC-_-PIPHorizontal2_rr-_-100423170-_-100404349-_-N
